apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: madhukamath29/node-mongo-db:02
          env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_PORT
        

--- 

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-node-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: tcp
      port: 27017
      targetPort: 27017
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
  
          
